version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 50
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
